{
 "title": "Eergy_Meter_3",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Live Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Phase Voltages",
   "type": "timeseries",
   "description": "Phase line to neutral voltage",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"Energy_Meter_Device_3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \" Phase 1 line to neutral voltage\" or r[\"_field\"] == \" Phase 2 line to neutral voltage\" or r[\"_field\"] == \" Phase 3 line to neutral voltage\")\n  |> drop(columns: [\"device\"])  // Exclude the ID column\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: if r._field == \" Phase 1 line to neutral voltage\" then \"Phase 1 Voltage\" else if r._field == \" Phase 2 line to neutral voltage\" then \"Phase 2 Voltage\" else \"Phase 3 Voltage\",\n      _value: r._value\n    }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Phase Currents",
   "type": "timeseries",
   "description": "Phase currents",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"Energy_Meter_Device_3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \" Phase 1 current\" or r[\"_field\"] == \" Phase 2 current\" or r[\"_field\"] == \" Phase 3 current\")\n  |> drop(columns: [\"device\"])\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: if r._field == \" Phase 1 current\" then \"Phase 1 Current\" else if r._field == \" Phase 2 current\" then \"Phase 2 Current\" else \"Phase 3 Current\",\n      _value: r._value\n    }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Energy_Meter_Device_3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \" Phase 1 power factor\" or r[\"_field\"] == \" Phase 2 power factor\" or r[\"_field\"] == \" Phase 3 power factor\")\n  |> drop(columns: [\"device\"])\n  |> last()\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: if r._field == \" Phase 1 power factor\" then \"Phase 1 Power Factor\" else if r._field == \" Phase 2 power factor\" then \"Phase 2 Power Factor\" else \"Phase 3 Power Factor\",\n      _value: r._value\n    }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Line to Line Votlages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"Energy_Meter_Device_3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \" Line 1 to Line 2 voltage\" or r[\"_field\"] == \" Line 2 to Line 3 voltage\" or r[\"_field\"] == \" Line 3 to Line 1 voltage\")\n  |> drop(columns: [\"device\"])\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: if r._field == \" Line 1 to Line 2 voltage\" then \"Line 1 to Line 2 Voltage\" else if r._field == \" Line 2 to Line 3 voltage\" then \"Line 2 to Line 3 Voltage\" else \"Line 3 to Line 1 Voltage\",\n      _value: r._value\n    }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Natural Currant",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Energy_Meter_Device_3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \" Neutral current\")\n  |> drop(columns: [\"device\"])\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Energy_Meter_Device_3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \" Frequency\")\n  |> drop(columns: [\"device\"])\n  |> last()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active Powers-Live",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Energy_Meter_Device_3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \" Phase 1 active power\" or r[\"_field\"] == \" Phase 2 active power\" or r[\"_field\"] == \" Phase 3 active power\")\n  |> drop(columns: [\"device\"])\n \n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: if r._field == \" Phase 1 active power\" then \"Phase 1 Power\" else if r._field == \" Phase 2 active power\" then \"Phase 2 Power\" else \"Phase 3 Power\",\n      _value: r._value\n    }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Hourly Energy Usage (Wh)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"Energy_Meter_Device_3\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_field\"] == \" Phase 1 active power\" or r[\"_field\"] == \" Phase 2 active power\" or r[\"_field\"] == \" Phase 3 active power\")\n  |> drop(columns: [\"device\"])\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: if r._field == \" Phase 1 active power\" then \"Phase 1 Energy Consumption\" else if r._field == \" Phase 2 active power\" then \"Phase 2 Energy Consumption\" else \"Phase 3 Energy Consumption\",\n      _value: r._value\n    }))\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)  // Aggregating by hour and summing the power over each hour\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: r._field,\n      _value: r._value / 1000.0  // Converting from watts to kilowatt-hours (kWh)\n    }))\n  |> yield(name: \"energy\")\n"
    }
   ]
  },
  {
   "title": "Daily Energy Usage (kWh)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Energy_Meter_Device_3\")\n  |> range(start: -8d)\n  |> filter(fn: (r) => r[\"_field\"] == \" Phase 1 active power\" or r[\"_field\"] == \" Phase 2 active power\" or r[\"_field\"] == \" Phase 3 active power\")\n  |> drop(columns: [\"device\"])\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: if r._field == \" Phase 1 active power\" then \"Phase 1 Energy Consumption\" \n              else if r._field == \" Phase 2 active power\" then \"Phase 2 Energy Consumption\" \n              else \"Phase 3 Energy Consumption\",\n      _value: float(v: r._value)  // Ensure _value is treated as a float\n    }))\n  |> aggregateWindow(every: 24h, fn: mean, createEmpty: false)  // Aggregating by day and calculating the mean power\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: r._field,  // Retain the new field name from the previous map\n      _value: r._value * 24.0 // Multiply by 24.0 to ensure its treated as a float\n    }))\n  |> yield(name: \"energy\")\n"
    }
   ]
  }
 ]
}